{% set version = "2.0.1" %}

package:
  name: termcolor
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/termcolor/termcolor-{{ version }}.tar.gz
  md5: a15736cb3634a61b077681777d1d6fdf

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6

  run:
    - python >=3.6

test:
  imports:
    - termcolor

about:
  home: http://pypi.python.org/pypi/termcolor
  license: MIT
  license_file: COPYING.txt
  summary: ANSII Color formatting for output in terminal.

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - k-dominik
