{% set version = "2.1.0" %}

package:
  name: termcolor
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/termcolor/termcolor-{{ version }}.tar.gz
  md5: 04e4981838535169d19d26a14a76af17

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - hatch-vcs
    - hatchling

  run:
    - python >=3.7

test:
  imports:
    - termcolor

about:
  home: https://github.com/termcolor/termcolor
  license: MIT
  license_file: COPYING.txt
  summary: ANSI color formatting for output in terminal

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - k-dominik
