travis:
  secure:
    BINSTAR_TOKEN: 2DoSdFEdoouo8zlDbdAuEw16sZkhmLqBkm3z50Oca1SKX7IB7VmBFeJbYA4Mckd9jhzZMj11YwI9+0xPb1JDF4VyzqaYOvhpGcNLZOg1/b+Y6o5Q0EF4MTw2PzEx1ojbCOMyFWDfBxaT/TSYny+kygdy9Hq+Qg/KI/QPoIwOk9UkvP+N2xvAopw2zx5sV8yuYZ0zXttbsISEYLEEKPB1WRdMN5RT7tOgPk20urpfSj2CRODdw5401XabiNwRz3ZDkWqVTH/cPPKRHvSM00NQRmQ+I66xJauZ5/hFdM/7gN6OPpXO6/gxdKPU/80V4q8Bj5T6bPvKZvVzXrgGb6EWvhQQPb0V1QIN06xeQ3FGpugGpQjP0VGErroXGHWqxF1uLxCN3v5Au4vZp0uMhlfSwvZFF2H32vNrIPiLkhgnSaT+gZ+EI23QCIpMIbs8aANCWfom5Bs82inmn9NakvlVVqg1pYKN5pNWr6GOSqaZ6jbicC0PVEkf33YuC+KCVEcO0+DaKKDGvSg46cg8MWE0C6CamRgiCzm6LGnqg0vYwKhMSySoL2GVt1lW8HfCo4oF66olZ+vjx7B+HiGCoP/8r/qiO7/DYwvHR8IVBn/IQ7iqoevy0p3ejSc7UKdJedeho7p3WHTYLuePSrDhL9H/uof/qtZKWA+RYIqOR0lYM0s=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
